### ISSUE TITLE
fix score.py bug

### ISSUE THREAD

**Issue by TransformersWsz** [alexa/alexa-with-dstc10-track2-dataset#4]
# Question about task1
There may be a bug in line 106 of the file `score.py`. We think we should limit the maximum list length of `pred_val` to `K` here, while now the list of predictions could be infinitely long. It is possible to use brute force method to keep `pred_val` right, affect the fairness of the competition.

# Suggestion
We update the file `score.py` by adding parameter `K` to limit the length of `pred_val`. Details can be seen in `task1/baseline/README.md` and `task1/scripts/scores.py`
___
We have open a PR on your github repo. Please check it. Thansk.

**Comment by seokhwankim** [comment]
As commented in your pull request, we've updated `scores.py` with the partial score considering any false positive/negative in predicted values. Please find more details from https://github.com/alexa/alexa-with-dstc10-track2-dataset/commit/d556d557b302f76f35fd69a79ea17531be2c8c7a. Thanks!
